# Generated by Django 3.1.1 on 2020-09-03 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.TextField(max_length=30)),
                ('nom', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='covoiturage.personne')),
                ('nbre_place', models.IntegerField()),
            ],
            bases=('covoiturage.personne',),
        ),
        migrations.CreateModel(
            name='Passager',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='covoiturage.personne')),
            ],
            bases=('covoiturage.personne',),
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.TextField(max_length=10)),
                ('arrive', models.TextField(max_length=10)),
                ('prix', models.IntegerField(default=4000)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covoiturage.conducteur')),
            ],
        ),
        migrations.CreateModel(
            name='Constituer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covoiturage.trajet')),
                ('passager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covoiturage.passager')),
            ],
        ),
    ]
