# Generated by Django 3.1.1 on 2020-09-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='passagers',
            field=models.ManyToManyField(to='covoiturage.Passager'),
        ),
        migrations.DeleteModel(
            name='Constituer',
        ),
    ]
